import { Sun, Waves } from 'lucide-react';

import {
  defaultCrossLinkIcons,
  defaultWhyCards,
  type CityLandingEnConfig,
} from '@/components/seo/city-landing-page-en';

export const splitEnPageData: CityLandingEnConfig = {
  city: 'Split',
  route: '/cuvanje-pasa-split/en',
  title: 'Dog Sitting in Split — Find a Trusted Sitter',
  description:
    'Find pet sitters in Split. Dog sitting in your neighborhood — Bačvice, Firule, Marjan, Spinut, Solin and surroundings. Send an inquiry online.',
  keywords: ['dog sitting split', 'pet sitter split', 'pet care split', 'dog sitter split', 'dog walking split', 'day care dogs split'],
  openGraphDescription: 'Find pet sitters in Split. Boarding, walks and day care for dogs in your neighborhood.',
  heroBadgeLabel: 'Split, Croatia',
  heroBadgeIcon: Sun,
  heroBadgeClassName: 'bg-blue-100 dark:bg-blue-900/40 text-blue-700 dark:text-blue-300 hover:bg-blue-100',
  heroSectionClassName: 'bg-gradient-to-br from-blue-50 via-white to-orange-50 dark:from-blue-950/20 dark:via-background dark:to-orange-950/20',
  heroTitle: 'Dog Sitting in Split',
  heroDescription: 'Find pet sitters in Split and the surrounding area. Compare pet sitter profiles while you are away or at work.',
  heroCtaLabel: 'Find a sitter in Split',
  searchCity: 'Split',
  introTitle: 'Dog Sitting in Split — Everything You Need to Know',
  introParagraphs: [
    'Split is the second largest city in Croatia with a rich Mediterranean culture and a warm climate that favors an active outdoor lifestyle — for both people and their pets. However, life in a Dalmatian city also brings specific challenges for dog owners. Summer heat, tourist crowds and lack of green spaces in the narrow city center make finding a reliable pet sitter extremely important.',
    'PetPark offers a solution for all Split dog owners. Our platform connects you with experienced sitters who know the city, understand the needs of dogs in a Mediterranean climate and offer services tailored to your needs. Whether you need someone to care for your dog while you are on holiday, or you need daily help with walks during the hot summer days — on PetPark you will find the right person.',
    'It is especially important to note that Split experiences a significant temperature increase during the summer months. Our experienced sitters know that walks need to be organized early in the morning or late in the evening, that dogs must always have access to fresh water and that shade is essential during the hottest part of the day. This knowledge and experience makes the difference between an average and an excellent sitter.',
  ],
  neighborhoodsTitle: "Dog Sitting Across Split's Neighborhoods",
  neighborhoods: [
    { name: 'Bačvice', desc: 'Popular beach, close to the city center' },
    { name: 'Firule', desc: 'Quiet neighborhood with a park and beach' },
    { name: 'Marjan', desc: 'Park-forest ideal for long walks' },
    { name: 'Spinut', desc: 'Near Marjan and ACI marina' },
    { name: 'Meje', desc: 'Seaside promenades and Marjan access' },
    { name: 'Solin', desc: 'Near the Jadro river, green surroundings' },
    { name: 'Žnjan', desc: 'Long promenade and dog-friendly beach' },
    { name: 'Stobreč', desc: 'Quiet suburb with sea access' },
    { name: 'Split 3', desc: 'Central location, parks nearby' },
  ],
  neighborhoodIconColorClass: 'text-blue-500',
  neighborhoodIconBgClass: 'bg-blue-100 dark:bg-blue-900/30',
  highlightsTitle: 'Best Places for Dog Walking in Split',
  highlightsIntroParagraphs: [
    'Marjan park-forest is one of the most familiar locations for dog walking in Split. With over 300 hectares of forested area, kilometers of trails and fresh air, Marjan provides an escape from the city bustle. The trails are varied — from an easy seaside promenade to more demanding mountain paths up the hill. Our sitters especially value early morning walks on Marjan when the temperature is pleasant and the trails are empty.',
    'The Žnjan promenade is popular for evening walks along the sea. Žnjan beach also has areas that are dog-tolerant, especially outside the main tourist season. The Jadro river in Solin offers a green environment with shade along the water, while Sustipan is a small but beautiful park at the tip of the Marjan peninsula with views of the sea and islands.',
  ],
  highlights: [
    { name: 'Marjan Park-Forest', feature: 'Forests, trails, fresh air' },
    { name: 'Žnjan Promenade', feature: 'Along the sea, long trail' },
    { name: 'Jadro River (Solin)', feature: 'Green corridors along water' },
    { name: 'Sustipan', feature: 'Sea and island views' },
  ],
  highlightsPanelClassName: 'bg-blue-50 dark:bg-blue-950/20',
  highlightsIcon: Waves,
  highlightsIconClass: 'text-blue-600',
  tipsTitle: 'Tips for Dog Owners in Split',
  tipsParagraphs: [
    'Split summers can be challenging for dogs. Temperatures easily exceed 35 degrees, and asphalt can heat up to dangerous levels. Good sitters in Split know that walks must be planned early in the morning before 9 AM or in the evening after 7 PM. In between, the dog should be kept cool, with access to fresh water and preferably air conditioning.',
    'If you are planning a trip during summer, book a sitter as early as possible — ideally 2–3 weeks in advance. Summer is peak season and the most sought-after sitters fill up quickly. Introduce the sitter to your dog before the booking and be sure to leave detailed instructions about feeding, medication and special needs. With PetPark you can compare profiles and agree on details in one place, with customer support available Mon–Sat 8 AM–8 PM.',
  ],
  whyTitle: 'Why Split Owners Choose PetPark',
  whyCards: [defaultWhyCards.verifiedProfiles, defaultWhyCards.securePlatform, defaultWhyCards.localSitters],
  internalLinksEyebrow: 'Next Step',
  internalLinksTitle: 'Explore Split and Related Services',
  internalLinksDescription: 'From Split you can quickly jump to related services, filtered search routes and other city pages.',
  faqTitle: 'Frequently Asked Questions',
  faqs: [
    {
      q: 'How much does dog sitting cost in Split?',
      a: 'Dog sitting prices in Split range from 12 to 28 euros per day. Overnight boarding typically costs €16–25, day care €12–18, and walks start from €8 per walk. During the summer season prices may be slightly higher due to increased demand.',
    },
    {
      q: 'Are there pet sitters in Split who accept dogs during summer?',
      a: 'You can compare available sitter profiles in Split and send an inquiry for the dates you need. We recommend booking in advance because summer is the busiest period.',
    },
    {
      q: 'Can a sitter walk my dog on Marjan?',
      a: 'Of course! Marjan is a favorite location for dog walking in Split. Many of our sitters from the Spinut, Meje and Varoš neighborhoods regularly walk dogs on Marjan trails. Fresh air, shade and nature make Marjan ideal for long walks.',
    },
    {
      q: 'How do I book a sitter in Split through PetPark?',
      a: 'Simply search for sitters in Split on our platform, browse profiles, reviews and prices. Send an inquiry for your desired dates, arrange a meet-and-greet and confirm the booking. The entire process takes just a few minutes.',
    },
  ],
  crossLinksTitle: 'Dog Sitting in Other Cities',
  crossLinks: [
    {
      href: '/cuvanje-pasa-zagreb',
      title: 'Zagreb',
      description: 'Sitters in Zagreb neighborhoods',
      icon: defaultCrossLinkIcons.city,
      iconColor: 'text-orange-500',
      hoverBorderClass: 'hover:border-orange-300',
      hoverTextClass: 'group-hover:text-orange-600',
    },
    {
      href: '/cuvanje-pasa-rijeka',
      title: 'Rijeka',
      description: 'Sitters in Rijeka neighborhoods',
      icon: defaultCrossLinkIcons.city,
      iconColor: 'text-teal-500',
      hoverBorderClass: 'hover:border-teal-300',
      hoverTextClass: 'group-hover:text-teal-600',
    },
    {
      href: '/njega?city=Split',
      title: 'Grooming in Split',
      description: 'Haircuts, bathing and care',
      icon: defaultCrossLinkIcons.grooming,
      iconColor: 'text-pink-500',
      hoverBorderClass: 'hover:border-pink-300',
      hoverTextClass: 'group-hover:text-pink-600',
    },
    {
      href: '/dresura?city=Split',
      title: 'Dog Training in Split',
      description: 'Trainers and programs',
      icon: defaultCrossLinkIcons.training,
      iconColor: 'text-indigo-500',
      hoverBorderClass: 'hover:border-indigo-300',
      hoverTextClass: 'group-hover:text-indigo-600',
    },
  ],
  finalCtaSectionClassName: 'bg-gradient-to-r from-blue-500 to-teal-500 py-16',
  finalCtaTitle: 'Find a Sitter in Split',
  finalCtaDescription: 'Sitter profiles across Split neighborhoods are available for comparison and inquiry. Send an inquiry quickly and easily.',
  finalCtaButtonClassName: 'bg-white text-blue-600 hover:bg-white/90 rounded-full px-8 font-semibold',
  finalCtaLabel: 'Browse sitters in Split',
  localBusinessName: 'PetPark — Dog Sitting in Split',
  localBusinessDescription: 'Find pet sitter profiles for dog sitting in Split. Compare options and send an inquiry online.',
  addressRegion: 'Splitsko-dalmatinska županija',
  latitude: 43.5081,
  longitude: 16.4402,
};
