import { MapPin, TreePine } from 'lucide-react';

import {
  defaultCrossLinkIcons,
  defaultWhyCards,
  type CityLandingEnConfig,
} from '@/components/seo/city-landing-page-en';

export const zagrebEnPageData: CityLandingEnConfig = {
  city: 'Zagreb',
  route: '/cuvanje-pasa-zagreb/en',
  title: 'Dog Sitting in Zagreb — Find a Trusted Sitter',
  description:
    'Find experienced and verified pet sitters in Zagreb. Dog sitting in your neighborhood — Maksimir, Trešnjevka, Novi Zagreb, Dubrava and more. Send an inquiry online.',
  keywords: ['dog sitting zagreb', 'pet sitter zagreb', 'pet care zagreb', 'dog sitter zagreb', 'dog walking zagreb', 'day care dogs zagreb'],
  openGraphDescription: 'Find verified pet sitters in Zagreb. Boarding, walks and day care for dogs in your neighborhood.',
  heroBadgeLabel: 'Zagreb, Croatia',
  heroBadgeIcon: MapPin,
  heroBadgeClassName: 'bg-orange-100 dark:bg-orange-900/40 text-orange-700 dark:text-orange-300 hover:bg-orange-100',
  heroSectionClassName: 'bg-gradient-to-br from-orange-50 via-white to-teal-50 dark:from-orange-950/20 dark:via-background dark:to-teal-950/20',
  heroTitle: 'Dog Sitting in Zagreb',
  heroDescription: 'Find verified and experienced pet sitters in your Zagreb neighborhood. Boarding, day care, walks and visits — all in one place.',
  heroCtaLabel: 'Find a sitter in Zagreb',
  searchCity: 'Zagreb',
  introTitle: 'Why Choose PetPark for Dog Sitting in Zagreb?',
  introParagraphs: [
    'Zagreb is a city of over 800,000 people and tens of thousands of pets. Every dog owner at some point needs a reliable person to take care of their pet — whether traveling on holiday, dealing with work commitments, or simply needing help with daily walks. PetPark connects dog owners in Zagreb with verified and experienced pet sitters who provide professional care in a comfortable environment.',
    'Our platform covers all Zagreb neighborhoods and city districts. Whether you live in Trešnjevka, Maksimir, Novi Zagreb, Dubrava, Jarun, Trnje or Stenjevec — on PetPark you will find a sitter near your home. This is especially important because dogs feel better when they stay in a familiar environment or at least close to it.',
  ],
  neighborhoodsTitle: "Dog Sitting Across Zagreb's Neighborhoods",
  neighborhoods: [
    { name: 'Maksimir', desc: 'Near Maksimir park-forest, ideal for walks' },
    { name: 'Trešnjevka', desc: 'Central location, plenty of green spaces' },
    { name: 'Novi Zagreb', desc: 'Bundek, Savica and spacious parks' },
    { name: 'Dubrava', desc: 'Quiet district with a green setting' },
    { name: 'Jarun', desc: 'Lake Jarun — paradise for active dogs' },
    { name: 'Stenjevec', desc: 'Western part of the city, near Medvednica' },
    { name: 'Trnje', desc: 'Close to the Sava embankment and promenades' },
    { name: 'Črnomerec', desc: 'Access to Medvednica forest trails' },
    { name: 'Sesvete', desc: 'Rural setting, spacious yards' },
  ],
  neighborhoodIconColorClass: 'text-orange-500',
  neighborhoodIconBgClass: 'bg-orange-100 dark:bg-orange-900/30',
  highlightsTitle: 'Popular Parks for Dog Walking in Zagreb',
  highlightsIntroParagraphs: [
    'Zagreb is rich in green spaces that are perfect for walks and play with your pet. Maksimir park-forest is the largest and most famous city park with kilometers of trails through forest and grassy areas. Many Zagreb sitters use Maksimir for long walks because it offers plenty of space where dogs can safely run and explore.',
    'Lake Jarun is a favorite destination for owners of active dogs. Gravel beaches and paths around the lake provide perfect terrain for running, swimming and play. Bundek in Novi Zagreb is a smaller but equally popular option with maintained paths around the lake. Park Ribnjak in the city center, Tuškanac and Zelengaj on the slopes of Medvednica, and the Sava embankment that stretches through the entire city — all are locations that our sitters regularly use for walking your pets.',
  ],
  highlights: [
    { name: 'Maksimir Park-Forest', feature: 'Kilometers of forest trails' },
    { name: 'Lake Jarun', feature: 'Beaches and lakeside paths' },
    { name: 'Bundek', feature: 'Maintained paths, peaceful atmosphere' },
    { name: 'Sava Embankment', feature: 'Long walks along the river' },
  ],
  highlightsPanelClassName: 'bg-teal-50 dark:bg-teal-950/20',
  highlightsIcon: TreePine,
  highlightsIconClass: 'text-teal-600',
  tipsTitle: 'Tips for Dog Owners in Zagreb',
  tipsParagraphs: [
    'If you are looking for a pet sitter in Zagreb for the first time, here are some useful tips. First of all, book a sitter at least a week in advance, especially during the summer months and holidays when demand is highest. Arrange a meet-and-greet with a potential sitter so your dog can get used to the new person. Prepare written instructions about feeding, medication and your pet\'s habits.',
    'It is important to know that Zagreb has rules about keeping dogs in public spaces. Dogs must be on a leash in parks and on streets, except in specially designated off-leash areas. Picking up after your dog is mandatory — your sitter will of course know this, but it is good for you to be familiar with the rules too. Zagreb also has several designated "dog parks" with fences where dogs can run freely, including one at Jarun and in Mladenaca park.',
    'By choosing a verified sitter on PetPark you get additional peace of mind. All our sitters undergo identity verification, have ratings and reviews from previous users, and PetPark offers insurance for every booking. This means you can travel with confidence knowing your pet is in safe hands.',
  ],
  whyTitle: 'Why Zagreb Owners Choose PetPark',
  whyCards: [defaultWhyCards.verifiedProfiles, defaultWhyCards.clearArrangements, defaultWhyCards.quickFirstStep],
  internalLinksEyebrow: 'Next Step',
  internalLinksTitle: 'Explore Zagreb and Other Cities',
  internalLinksDescription:
    'Starting from Zagreb, you can quickly jump to related services, search and other city pages without navigating through the menu.',
  faqTitle: 'Frequently Asked Questions',
  faqs: [
    {
      q: 'How much does dog sitting cost in Zagreb?',
      a: 'Dog sitting prices in Zagreb range from 12 to 30 euros per day, depending on the type of service. Overnight boarding typically costs €18–25, day care €12–20, and walks start from €8 per walk. On PetPark each sitter sets their own prices, so you can find an option that fits your budget.',
    },
    {
      q: 'How do I find a reliable pet sitter in Zagreb?',
      a: 'On PetPark, sitters go through a basic profile and identity check before being published. We recommend checking reviews from other users, arranging a meet-and-greet before booking, and looking for profiles marked "Top pick".',
    },
    {
      q: 'Can I get daily updates about my dog?',
      a: 'Yes! Most sitters on PetPark send regular updates with photos and videos of your pet. You can agree on the frequency of updates before the sitting begins. Some sitters also offer GPS walk tracking.',
    },
    {
      q: 'What if my dog gets sick during a sitting?',
      a: 'All PetPark sitters have instructions for handling emergencies. The sitter will contact you immediately and you respond together. We recommend arranging a vet and emergency contact in advance.',
    },
  ],
  crossLinksTitle: 'Dog Sitting in Other Cities',
  crossLinks: [
    {
      href: '/cuvanje-pasa-rijeka',
      title: 'Rijeka',
      description: 'Sitters in Rijeka neighborhoods',
      icon: defaultCrossLinkIcons.city,
      iconColor: 'text-teal-500',
      hoverBorderClass: 'hover:border-teal-300',
      hoverTextClass: 'group-hover:text-teal-600',
    },
    {
      href: '/cuvanje-pasa-split',
      title: 'Split',
      description: 'Sitters in Split neighborhoods',
      icon: defaultCrossLinkIcons.city,
      iconColor: 'text-blue-500',
      hoverBorderClass: 'hover:border-blue-300',
      hoverTextClass: 'group-hover:text-blue-600',
    },
    {
      href: '/njega?city=Zagreb',
      title: 'Grooming in Zagreb',
      description: 'Haircuts, bathing and care',
      icon: defaultCrossLinkIcons.grooming,
      iconColor: 'text-pink-500',
      hoverBorderClass: 'hover:border-pink-300',
      hoverTextClass: 'group-hover:text-pink-600',
    },
    {
      href: '/dresura?city=Zagreb',
      title: 'Dog Training in Zagreb',
      description: 'Trainers and programs',
      icon: defaultCrossLinkIcons.training,
      iconColor: 'text-indigo-500',
      hoverBorderClass: 'hover:border-indigo-300',
      hoverTextClass: 'group-hover:text-indigo-600',
    },
  ],
  finalCtaSectionClassName: 'bg-gradient-to-r from-orange-500 to-teal-500 py-16',
  finalCtaTitle: 'Find the Perfect Sitter in Zagreb',
  finalCtaDescription: 'Verified profiles across all Zagreb neighborhoods are waiting for your inquiry. Send an inquiry online in just a few clicks.',
  finalCtaButtonClassName: 'bg-white text-orange-600 hover:bg-white/90 rounded-full px-8 font-semibold',
  finalCtaLabel: 'Browse sitters in Zagreb',
  localBusinessName: 'PetPark — Dog Sitting in Zagreb',
  localBusinessDescription: 'Find reliable pet sitters for dog sitting in Zagreb. Verified profiles and online inquiries.',
  addressRegion: 'Grad Zagreb',
  latitude: 45.815,
  longitude: 15.9819,
};
