import { Anchor, Mountain } from 'lucide-react';

import {
  defaultCrossLinkIcons,
  defaultWhyCards,
  type CityLandingEnConfig,
} from '@/components/seo/city-landing-page-en';

export const rijekaEnPageData: CityLandingEnConfig = {
  city: 'Rijeka',
  route: '/cuvanje-pasa-rijeka/en',
  title: 'Dog Sitting in Rijeka — Find a Trusted Sitter',
  description:
    'Find experienced and verified pet sitters in Rijeka. Dog sitting in your neighborhood — Trsat, Kantrida, Sušak, Kozala, Turnić and surroundings. Send an inquiry online.',
  keywords: ['dog sitting rijeka', 'pet sitter rijeka', 'pet care rijeka', 'dog sitter rijeka', 'dog walking rijeka', 'day care dogs rijeka'],
  openGraphDescription: 'Find verified pet sitters in Rijeka. Boarding, walks and day care for dogs in your neighborhood.',
  heroBadgeLabel: 'Rijeka, Croatia',
  heroBadgeIcon: Anchor,
  heroBadgeClassName: 'bg-teal-100 dark:bg-teal-900/40 text-teal-700 dark:text-teal-300 hover:bg-teal-100',
  heroSectionClassName: 'bg-gradient-to-br from-teal-50 via-white to-blue-50 dark:from-teal-950/20 dark:via-background dark:to-blue-950/20',
  heroTitle: 'Dog Sitting in Rijeka',
  heroDescription: 'Find reliable pet sitters in Rijeka and the surrounding area. From Trsat to Kantrida — your pet is in safe hands.',
  heroCtaLabel: 'Find a sitter in Rijeka',
  searchCity: 'Rijeka',
  introTitle: 'Dog Sitting in Rijeka — A Seaside City with a Big Heart for Pets',
  introParagraphs: [
    'Rijeka is the third largest city in Croatia, situated on the northern Adriatic between the sea and the mountains. This unique position makes Rijeka an exceptional city for dog owners — on one side you have access to the seafront and the Lungo mare promenade, and on the other side hills and forests that offer endless possibilities for walks and adventures with your four-legged friend.',
    'The people of Rijeka are known for their love of animals. The city has an active community of dog owners and an increasing number of pet-friendly amenities. However, the specific terrain of the city — hills, stairs and narrow streets in the old part — makes finding the right sitter who knows the city even more important. PetPark helps you find a sitter who lives in your neighborhood, knows the local parks and trails, and understands the specifics of life with a dog in Rijeka.',
    'Whether you live on Trsat with a view of the Kvarner bay, in quiet Sušak, on windy Kantrida by the sea or in the lively city center — on PetPark you will find an experienced sitter who will care for your pet as their own. Our community of sitters in Rijeka is constantly growing, and each one undergoes verification that includes identity and animal experience checks.',
  ],
  neighborhoodsTitle: "Dog Sitting Across Rijeka's Neighborhoods",
  neighborhoods: [
    { name: 'Trsat', desc: 'Kvarner bay views, near the forest' },
    { name: 'Kantrida', desc: 'By the sea, beach and Lungo mare' },
    { name: 'Sušak', desc: 'Quiet neighborhood, well connected' },
    { name: 'Kozala', desc: 'Green spaces, peaceful surroundings' },
    { name: 'Turnić', desc: 'Park areas, close to the center' },
    { name: 'Pećine', desc: 'Along the coast, seaside promenades' },
    { name: 'Zamet', desc: 'Quiet suburb with green areas' },
    { name: 'Drenova', desc: 'Hilly setting, fresh air' },
    { name: 'Škurinje', desc: 'Near forests and mountain trails' },
  ],
  neighborhoodIconColorClass: 'text-teal-500',
  neighborhoodIconBgClass: 'bg-teal-100 dark:bg-teal-900/30',
  highlightsTitle: 'Best Places for Dog Walking in Rijeka',
  highlightsIntroParagraphs: [
    'The Lungo mare promenade is one of the most beautiful coastal walkways in Croatia and is perfect for daily dog walks. It stretches from Opatija to Volosko, passes through Kantrida and offers spectacular views of the Kvarner bay. Many of our sitters use this promenade for morning and evening walks because it combines the sea, fresh air and flat terrain.',
    'The Trsat forest above the neighborhood of the same name offers beautiful trails through dense forest with views of the city and the bay. Park Mlaka in the city center is smaller but practical for quick walks. For more active dogs, the Rijeka surroundings offer access to mountain trails towards Učka and Gorski kotar, where your pet can enjoy nature far from the city bustle. Preluk is a popular dog-friendly beach where dogs can enjoy the sea during warmer months.',
  ],
  highlights: [
    { name: 'Lungo mare', feature: 'Coastal promenade, flat terrain' },
    { name: 'Trsat Forest', feature: 'Forest trails above the city' },
    { name: 'Preluk', feature: 'Dog-friendly beach' },
    { name: 'Park Mlaka', feature: 'City park, quick walks' },
  ],
  highlightsPanelClassName: 'bg-teal-50 dark:bg-teal-950/20',
  highlightsIcon: Mountain,
  highlightsIconClass: 'text-teal-600',
  tipsTitle: 'Tips for Dog Owners in Rijeka',
  tipsParagraphs: [
    'Rijeka is known for the bura — a strong northern wind that can be challenging for walks with smaller dogs. Experienced Rijeka sitters know how to adjust walks according to weather conditions and which routes to use when the bura is blowing. In winter it is important to protect dog paws from salt on treated roads, while in summer you need to watch out for hot asphalt, especially in the lower parts of the city.',
    'PetPark was actually founded in Rijeka, so we have a special connection with this city and its community of pet owners. Our Rijeka sitters were among the first to join the platform and have extensive experience. We recommend taking advantage of the opportunity for a meet-and-greet with the sitter before booking — many sitters offer a free introductory meeting where they can get to know your dog and agree on all care details.',
  ],
  whyTitle: 'Why Rijeka Owners Choose PetPark',
  whyCards: [defaultWhyCards.verifiedProfiles, defaultWhyCards.foundedInRijeka, defaultWhyCards.supportMonSat],
  internalLinksEyebrow: 'Next Step',
  internalLinksTitle: 'Explore Rijeka and Related PetPark Routes',
  internalLinksDescription:
    'Rijeka already has sitting, grooming and training listings — here we connect you to real next steps rather than generic SEO filler.',
  faqTitle: 'Frequently Asked Questions',
  faqs: [
    {
      q: 'How much does dog sitting cost in Rijeka?',
      a: 'Dog sitting prices in Rijeka range from 10 to 25 euros per day. Overnight boarding typically costs €15–22, day care €10–16, and walks start from €7 per walk. Rijeka is generally more affordable than Zagreb and Split for pet care services.',
    },
    {
      q: 'What are the best neighborhoods for dogs in Rijeka?',
      a: 'Trsat is an excellent choice thanks to its proximity to the forest and quiet surroundings. Kantrida offers access to the beach and the Lungo mare promenade. Kozala and Turnić have green spaces suitable for walks. Sušak is well-connected and has several smaller parks ideal for daily walks.',
    },
    {
      q: 'Does Rijeka have dog-friendly beaches?',
      a: 'Yes! Rijeka and its surroundings have several dog-friendly beaches, especially outside the tourist season. Kantrida and Preluk are popular options. Our sitters know all the locations where dogs are welcome and adjust walks accordingly.',
    },
    {
      q: 'Can I find a sitter for emergencies in Rijeka?',
      a: 'Yes, on PetPark you can find sitters who accept short-notice bookings. Use the "quick response" filter in the search to find sitters who typically respond within an hour. For the best results we still recommend booking at least a few days in advance.',
    },
  ],
  crossLinksTitle: 'Dog Sitting in Other Cities',
  crossLinks: [
    {
      href: '/cuvanje-pasa-zagreb',
      title: 'Zagreb',
      description: 'Sitters in Zagreb neighborhoods',
      icon: defaultCrossLinkIcons.city,
      iconColor: 'text-orange-500',
      hoverBorderClass: 'hover:border-orange-300',
      hoverTextClass: 'group-hover:text-orange-600',
    },
    {
      href: '/cuvanje-pasa-split',
      title: 'Split',
      description: 'Sitters in Split neighborhoods',
      icon: defaultCrossLinkIcons.city,
      iconColor: 'text-blue-500',
      hoverBorderClass: 'hover:border-blue-300',
      hoverTextClass: 'group-hover:text-blue-600',
    },
    {
      href: '/njega?city=Rijeka',
      title: 'Grooming in Rijeka',
      description: 'Haircuts, bathing and care',
      icon: defaultCrossLinkIcons.grooming,
      iconColor: 'text-pink-500',
      hoverBorderClass: 'hover:border-pink-300',
      hoverTextClass: 'group-hover:text-pink-600',
    },
    {
      href: '/dresura?city=Rijeka',
      title: 'Dog Training in Rijeka',
      description: 'Trainers and programs',
      icon: defaultCrossLinkIcons.training,
      iconColor: 'text-indigo-500',
      hoverBorderClass: 'hover:border-indigo-300',
      hoverTextClass: 'group-hover:text-indigo-600',
    },
  ],
  finalCtaSectionClassName: 'bg-gradient-to-r from-teal-500 to-blue-500 py-16',
  finalCtaTitle: 'Find the Perfect Sitter in Rijeka',
  finalCtaDescription: 'Trusted profiles across all Rijeka neighborhoods are waiting for your inquiry. Send an inquiry online quickly and easily.',
  finalCtaButtonClassName: 'bg-white text-teal-600 hover:bg-white/90 rounded-full px-8 font-semibold',
  finalCtaLabel: 'Browse sitters in Rijeka',
  localBusinessName: 'PetPark — Dog Sitting in Rijeka',
  localBusinessDescription: 'Find reliable pet sitters for dog sitting in Rijeka. Verified profiles and online inquiries.',
  addressRegion: 'Primorsko-goranska županija',
  latitude: 45.3271,
  longitude: 14.4422,
};
