/** @deprecated Fallback data — use lib/db/adoption.ts instead. */
export interface AdoptionPet {
  id: string;
  name: string;
  species: 'dog' | 'cat' | 'rabbit';
  breed: string;
  age_months: number;
  gender: 'male' | 'female';
  size: 'small' | 'medium' | 'large';
  weight_kg: number;
  color: string;
  sterilized: boolean;
  vaccinated: boolean;
  microchipped: boolean;
  good_with_kids: boolean;
  good_with_pets: boolean;
  urgent: boolean;
  description: string;
  personality: string;
  special_needs?: string;
  city: string;
  shelter_id: string;
  listed_at: string;
  image_gradient: string;
}

export interface Shelter {
  id: string;
  name: string;
  city: string;
  address: string;
  phone: string;
  email: string;
  working_hours: string;
}

export const shelters: Shelter[] = [
  {
    id: 'shelter-1',
    name: 'Azil Dumovec',
    city: 'Zagreb',
    address: 'Dumovečka ulica 56, 10000 Zagreb',
    phone: '+385 1 2345 678',
    email: 'info@azildumovec.hr',
    working_hours: 'Pon-Pet 08:00-16:00, Sub 09:00-13:00',
  },
  {
    id: 'shelter-2',
    name: 'Udruga Pobjede',
    city: 'Split',
    address: 'Ulica slobode 12, 21000 Split',
    phone: '+385 21 345 678',
    email: 'udruga.pobjede@gmail.com',
    working_hours: 'Pon-Pet 09:00-17:00',
  },
  {
    id: 'shelter-3',
    name: 'Azil Rijeka',
    city: 'Rijeka',
    address: 'Škurinjska cesta 18, 51000 Rijeka',
    phone: '+385 51 234 567',
    email: 'azil.rijeka@gmail.com',
    working_hours: 'Pon-Sub 08:00-15:00',
  },
  {
    id: 'shelter-4',
    name: 'Sklonište Osijek',
    city: 'Osijek',
    address: 'Industrijska ulica 8, 31000 Osijek',
    phone: '+385 31 456 789',
    email: 'skloniste.osijek@gmail.com',
    working_hours: 'Pon-Pet 08:00-16:00, Sub 09:00-12:00',
  },
  {
    id: 'shelter-5',
    name: 'Udruga Četiri šape',
    city: 'Zadar',
    address: 'Put Bokanjca 22, 23000 Zadar',
    phone: '+385 23 345 678',
    email: 'cetiri.sape@gmail.com',
    working_hours: 'Pon-Pet 09:00-16:00',
  },
];

export const mockAdoptionPets: AdoptionPet[] = [
  {
    id: 'adopt-1',
    name: 'Bubi',
    species: 'dog',
    breed: 'Mješanac (labrador)',
    age_months: 36,
    gender: 'male',
    size: 'large',
    weight_kg: 28,
    color: 'Smeđa',
    sterilized: true,
    vaccinated: true,
    microchipped: true,
    good_with_kids: true,
    good_with_pets: true,
    urgent: false,
    description: 'Bubi je veseli i energični pas koji obožava ljude. Pronađen je kao napušteni pas na cesti i zbrinut u azilu. Idealan je za aktivne obitelji koje vole šetnje i igru na otvorenom.',
    personality: 'Veseo, energičan, poslušan, voli vodu i igru loptom.',
    city: 'Zagreb',
    shelter_id: 'shelter-1',
    listed_at: '2025-12-15',
    image_gradient: 'from-amber-400 to-orange-500',
  },
  {
    id: 'adopt-2',
    name: 'Luna',
    species: 'cat',
    breed: 'Europska kratkodlaka',
    age_months: 18,
    gender: 'female',
    size: 'small',
    weight_kg: 4,
    color: 'Crno-bijela',
    sterilized: true,
    vaccinated: true,
    microchipped: false,
    good_with_kids: true,
    good_with_pets: false,
    urgent: false,
    description: 'Luna je mirna mačka koja voli maziti se i ležati na suncu. Najbolje se osjeća kao jedini ljubimac u kući. Savršena za mirnije domove.',
    personality: 'Mirna, umiljata, samostalna, voli visoke pozicije.',
    city: 'Split',
    shelter_id: 'shelter-2',
    listed_at: '2026-01-20',
    image_gradient: 'from-slate-400 to-blue-500',
  },
  {
    id: 'adopt-3',
    name: 'Rex',
    species: 'dog',
    breed: 'Njemački ovčar mix',
    age_months: 60,
    gender: 'male',
    size: 'large',
    weight_kg: 35,
    color: 'Crno-smeđa',
    sterilized: true,
    vaccinated: true,
    microchipped: true,
    good_with_kids: false,
    good_with_pets: false,
    urgent: true,
    description: 'Rex je ozbiljan i lojalan pas koji traži iskusnog vlasnika. Bio je policijski pas i nakon umirovljenja ostao je bez doma. Treba dom bez male djece i drugih životinja.',
    personality: 'Lojalan, inteligentan, zaštitničke naravi, treniran.',
    special_needs: 'Potrebna redovita tjelesna aktivnost i mentalna stimulacija.',
    city: 'Zagreb',
    shelter_id: 'shelter-1',
    listed_at: '2025-08-10',
    image_gradient: 'from-gray-600 to-amber-700',
  },
  {
    id: 'adopt-4',
    name: 'Mila',
    species: 'cat',
    breed: 'Perzijska mješanka',
    age_months: 84,
    gender: 'female',
    size: 'medium',
    weight_kg: 5,
    color: 'Siva',
    sterilized: true,
    vaccinated: true,
    microchipped: true,
    good_with_kids: true,
    good_with_pets: true,
    urgent: true,
    description: 'Mila je starija mačka čiji je vlasnik preminuo. Vrlo je nježna i mirna, navikla na život u stanu. Hitno traži novi dom jer u azilu pati od stresa.',
    personality: 'Nježna, tiha, voli ležati u krilu, ne zahtijeva puno aktivnosti.',
    special_needs: 'Kronični problemi s bubrezima — potrebna posebna dijeta.',
    city: 'Rijeka',
    shelter_id: 'shelter-3',
    listed_at: '2025-09-01',
    image_gradient: 'from-purple-400 to-indigo-500',
  },
  {
    id: 'adopt-5',
    name: 'Tarzan',
    species: 'dog',
    breed: 'Jack Russell terrier mix',
    age_months: 12,
    gender: 'male',
    size: 'small',
    weight_kg: 7,
    color: 'Bijelo-smeđa',
    sterilized: false,
    vaccinated: true,
    microchipped: false,
    good_with_kids: true,
    good_with_pets: true,
    urgent: false,
    description: 'Tarzan je mladi i razigrani psić koji je pronađen na ulici kao štene. Vrlo je društven i voli se igrati s drugim psima. Savršen za aktivne obitelji.',
    personality: 'Razigran, energičan, društven, brzo uči.',
    city: 'Osijek',
    shelter_id: 'shelter-4',
    listed_at: '2026-02-14',
    image_gradient: 'from-orange-300 to-yellow-400',
  },
  {
    id: 'adopt-6',
    name: 'Bella',
    species: 'dog',
    breed: 'Mješanac (pitbull tip)',
    age_months: 48,
    gender: 'female',
    size: 'medium',
    weight_kg: 22,
    color: 'Brindle (tigrasta)',
    sterilized: true,
    vaccinated: true,
    microchipped: true,
    good_with_kids: true,
    good_with_pets: false,
    urgent: false,
    description: 'Bella je nježna i odana kujica koja obožava ljude. Ima loš glas zbog rase, ali je zapravo prava mazilica. Idealna za obitelj koja joj može posvetiti pažnju.',
    personality: 'Nježna, odana, voli maziti se, pomalo plaha na početku.',
    city: 'Split',
    shelter_id: 'shelter-2',
    listed_at: '2025-11-05',
    image_gradient: 'from-rose-400 to-orange-500',
  },
  {
    id: 'adopt-7',
    name: 'Whiskers',
    species: 'cat',
    breed: 'Mačak s ulice',
    age_months: 24,
    gender: 'male',
    size: 'medium',
    weight_kg: 5.5,
    color: 'Narančasta (tabby)',
    sterilized: true,
    vaccinated: true,
    microchipped: false,
    good_with_kids: true,
    good_with_pets: true,
    urgent: false,
    description: 'Whiskers je tipični narančasti mačak — veseo, glasan i uvijek gladan. Voli društvo ljudi i drugih mačaka. Idealan za obitelj koja želi zabavnog ljubimca.',
    personality: 'Društven, glasan, znatiželjni istraživač, voli hranu.',
    city: 'Zagreb',
    shelter_id: 'shelter-1',
    listed_at: '2026-01-10',
    image_gradient: 'from-orange-400 to-amber-500',
  },
  {
    id: 'adopt-8',
    name: 'Kiki',
    species: 'rabbit',
    breed: 'Mini lop',
    age_months: 8,
    gender: 'female',
    size: 'small',
    weight_kg: 1.5,
    color: 'Bijela s sivim ušima',
    sterilized: true,
    vaccinated: true,
    microchipped: false,
    good_with_kids: true,
    good_with_pets: false,
    urgent: false,
    description: 'Kiki je slatki mini lop kunić koji je ostao bez vlasnika nakon preseljenja. Mirna je i voli da je se drži. Savršena za obitelj koja želi mirnog ljubimca.',
    personality: 'Mirna, radoznala, voli salatu i mrkvu, navikla na ljude.',
    city: 'Zadar',
    shelter_id: 'shelter-5',
    listed_at: '2026-03-01',
    image_gradient: 'from-pink-300 to-purple-400',
  },
  {
    id: 'adopt-9',
    name: 'Čarli',
    species: 'dog',
    breed: 'Beagle mix',
    age_months: 30,
    gender: 'male',
    size: 'medium',
    weight_kg: 14,
    color: 'Tricolor',
    sterilized: true,
    vaccinated: true,
    microchipped: true,
    good_with_kids: true,
    good_with_pets: true,
    urgent: false,
    description: 'Čarli je simpatični beagle mješanac s neodoljivim pogledom. Odličan je s djecom i drugim životinjama. Voli šetnje i istraživanje novih mirisa.',
    personality: 'Znatiželjan, prijateljski, voli šetnje, ponekad tvrdoglav.',
    city: 'Rijeka',
    shelter_id: 'shelter-3',
    listed_at: '2026-02-01',
    image_gradient: 'from-emerald-400 to-teal-500',
  },
  {
    id: 'adopt-10',
    name: 'Nera',
    species: 'cat',
    breed: 'Domaća crna mačka',
    age_months: 6,
    gender: 'female',
    size: 'small',
    weight_kg: 2.8,
    color: 'Crna',
    sterilized: false,
    vaccinated: true,
    microchipped: false,
    good_with_kids: true,
    good_with_pets: true,
    urgent: false,
    description: 'Nera je mlada crna mačkica koja čeka da joj netko da šansu. Crne mačke se teže udomljavaju, ali Nera je pravo blago — umiljata i razigrana.',
    personality: 'Umiljata, razigrana, voli loviti igračke, noćna istraživačica.',
    city: 'Osijek',
    shelter_id: 'shelter-4',
    listed_at: '2026-03-10',
    image_gradient: 'from-gray-700 to-violet-600',
  },
  {
    id: 'adopt-11',
    name: 'Bodri',
    species: 'dog',
    breed: 'Hrvatski ovčar',
    age_months: 144,
    gender: 'male',
    size: 'medium',
    weight_kg: 16,
    color: 'Crna kovrčava',
    sterilized: true,
    vaccinated: true,
    microchipped: true,
    good_with_kids: true,
    good_with_pets: true,
    urgent: true,
    description: 'Bodri je stariji hrvatski ovčar koji je cijeli život proveo na selu čuvajući ovce. Vlasnik se preselio u dom za starije i Bodri hitno traži novi dom.',
    personality: 'Miran, poslušan, odan, voli rutinu i šetnje.',
    special_needs: 'Artritis — potrebna umjerena aktivnost i dodatci za zglobove.',
    city: 'Zadar',
    shelter_id: 'shelter-5',
    listed_at: '2025-10-20',
    image_gradient: 'from-gray-800 to-slate-600',
  },
  {
    id: 'adopt-12',
    name: 'Snoopy',
    species: 'dog',
    breed: 'Dalmatiner mix',
    age_months: 4,
    gender: 'male',
    size: 'medium',
    weight_kg: 5,
    color: 'Bijela s crnim točkama',
    sterilized: false,
    vaccinated: true,
    microchipped: false,
    good_with_kids: true,
    good_with_pets: true,
    urgent: false,
    description: 'Snoopy je preslatko štene dalmatinera koje je pronađeno u kutiji ispred azila. Veseo je, razigran i spreman za avanture s novom obitelji.',
    personality: 'Bezbrižan, razigran, voli grickati cipele, puno energije.',
    city: 'Split',
    shelter_id: 'shelter-2',
    listed_at: '2026-03-15',
    image_gradient: 'from-sky-300 to-blue-500',
  },
  {
    id: 'adopt-13',
    name: 'Zara',
    species: 'dog',
    breed: 'Mješanac (malih pasmina)',
    age_months: 72,
    gender: 'female',
    size: 'small',
    weight_kg: 6,
    color: 'Krem',
    sterilized: true,
    vaccinated: true,
    microchipped: true,
    good_with_kids: false,
    good_with_pets: true,
    urgent: false,
    description: 'Zara je mirna kujica koja je došla iz lošeg držanja. Trebalo joj je vremena da se otvori, ali sada je prava mazilica. Traži strpljivog vlasnika bez male djece.',
    personality: 'Oprezna na početku, ali nježna kad stekne povjerenje. Voli šetnje i tihe večeri.',
    city: 'Zagreb',
    shelter_id: 'shelter-1',
    listed_at: '2025-12-01',
    image_gradient: 'from-yellow-300 to-amber-400',
  },
  {
    id: 'adopt-14',
    name: 'Miki',
    species: 'cat',
    breed: 'Sijamski mješanac',
    age_months: 36,
    gender: 'male',
    size: 'medium',
    weight_kg: 4.5,
    color: 'Seal point',
    sterilized: true,
    vaccinated: true,
    microchipped: true,
    good_with_kids: true,
    good_with_pets: true,
    urgent: false,
    description: 'Miki je pričljivi sijamski mješanac koji će vam uvijek reći što misli. Društven je, inteligentan i voli interaktivne igračke.',
    personality: 'Pričljiv, inteligentan, društven, voli igru i pažnju.',
    city: 'Rijeka',
    shelter_id: 'shelter-3',
    listed_at: '2026-02-20',
    image_gradient: 'from-amber-200 to-brown-400',
  },
  {
    id: 'adopt-15',
    name: 'Bruno',
    species: 'dog',
    breed: 'Mješanac (srednje veličine)',
    age_months: 24,
    gender: 'male',
    size: 'medium',
    weight_kg: 18,
    color: 'Smeđa',
    sterilized: true,
    vaccinated: true,
    microchipped: false,
    good_with_kids: true,
    good_with_pets: true,
    urgent: false,
    description: 'Bruno je prijateljski mješanac koji se slaže sa svima. Pronađen je zanemaren, ali nakon rehabilitacije je pravi veseljak. Savršen obiteljski pas.',
    personality: 'Prijateljski, veseo, voli se igrati, dobar s djecom.',
    city: 'Osijek',
    shelter_id: 'shelter-4',
    listed_at: '2026-01-25',
    image_gradient: 'from-amber-500 to-orange-600',
  },
  {
    id: 'adopt-16',
    name: 'Cici',
    species: 'cat',
    breed: 'Domaća dugodlaka',
    age_months: 48,
    gender: 'female',
    size: 'medium',
    weight_kg: 4.2,
    color: 'Bijelo-siva',
    sterilized: true,
    vaccinated: true,
    microchipped: false,
    good_with_kids: true,
    good_with_pets: false,
    urgent: false,
    description: 'Cici je elegantna mačka s prekrasnom dugom dlakom. Voli da je češljaju i maziti se, ali ne voli druge mačke. Idealna za dom bez drugih ljubimaca.',
    personality: 'Elegantna, umiljata, voli da je češljaju, pomalo diva.',
    city: 'Zadar',
    shelter_id: 'shelter-5',
    listed_at: '2026-02-10',
    image_gradient: 'from-slate-300 to-indigo-400',
  },
  {
    id: 'adopt-17',
    name: 'Floki',
    species: 'rabbit',
    breed: 'Nizozemski patuljasti',
    age_months: 14,
    gender: 'male',
    size: 'small',
    weight_kg: 1.2,
    color: 'Smeđe-bijela',
    sterilized: true,
    vaccinated: true,
    microchipped: false,
    good_with_kids: true,
    good_with_pets: false,
    urgent: false,
    description: 'Floki je mali kunić koji je ostao bez vlasnika jer se obitelj preselila u stan gdje nisu mogli imati kućne ljubimce. Miran je i naviknut na ljude.',
    personality: 'Miran, radoznao, voli istraživati sobu, jede iz ruke.',
    city: 'Zagreb',
    shelter_id: 'shelter-1',
    listed_at: '2026-03-05',
    image_gradient: 'from-amber-300 to-pink-400',
  },
  {
    id: 'adopt-18',
    name: 'Lola',
    species: 'dog',
    breed: 'Pudlica mix',
    age_months: 36,
    gender: 'female',
    size: 'small',
    weight_kg: 8,
    color: 'Bijela',
    sterilized: true,
    vaccinated: true,
    microchipped: true,
    good_with_kids: true,
    good_with_pets: true,
    urgent: false,
    description: 'Lola je pametna i živahna kujica koja brzo uči trikove. Hipoalergena dlaka čini je idealnom za ljude s alergijama. Voli društvo i ne voli biti sama.',
    personality: 'Pametna, živahna, voli učiti trikove, traži pažnju.',
    city: 'Split',
    shelter_id: 'shelter-2',
    listed_at: '2026-02-28',
    image_gradient: 'from-pink-200 to-rose-400',
  },
];

export function getShelterById(id: string): Shelter | undefined {
  return shelters.find((s) => s.id === id);
}

export function getAdoptionPetById(id: string): AdoptionPet | undefined {
  return mockAdoptionPets.find((p) => p.id === id);
}

export function getPetsByShelter(shelterId: string): AdoptionPet[] {
  return mockAdoptionPets.filter((p) => p.shelter_id === shelterId);
}

export function formatAge(months: number): string {
  if (months < 6) return `${months} mj.`;
  if (months < 12) return `${months} mj.`;
  const years = Math.floor(months / 12);
  const remaining = months % 12;
  if (remaining === 0) return `${years} god.`;
  return `${years} god. ${remaining} mj.`;
}

export function getAgeCategory(months: number): string {
  if (months < 6) return 'puppy';
  if (months < 24) return 'young';
  if (months < 96) return 'adult';
  return 'senior';
}

export function getAgeCategoryLabel(months: number): string {
  if (months < 6) return 'Štene/Mače';
  if (months < 24) return 'Mladi';
  if (months < 96) return 'Odrasli';
  return 'Senior';
}

export const SPECIES_EMOJI: Record<string, string> = {
  dog: '🐕',
  cat: '🐈',
  rabbit: '🐰',
};

export const SPECIES_LABEL: Record<string, string> = {
  dog: 'Pas',
  cat: 'Mačka',
  rabbit: 'Kunić',
};

export const GENDER_LABEL: Record<string, string> = {
  male: 'Muški',
  female: 'Ženski',
};

export const SIZE_LABEL: Record<string, string> = {
  small: 'Mali',
  medium: 'Srednji',
  large: 'Veliki',
};
