/** @deprecated Fallback data — use lib/db/dog-friendly.ts instead. */
export interface DogFriendlyLocation {
  id: string;
  name: string;
  city: string;
  category: 'cafe' | 'restaurant' | 'beach' | 'park' | 'hotel' | 'shop';
  address: string;
  lat: number;
  lng: number;
  rating: number;
  reviewCount: number;
  description: string;
  tags: string[];
  googleMapsUrl: string;
  imageGradient: string;
}

export const CATEGORY_LABELS: Record<DogFriendlyLocation['category'], string> = {
  cafe: '☕ Kafić',
  restaurant: '🍽️ Restoran',
  beach: '🏖️ Plaža',
  park: '🌳 Park',
  hotel: '🏨 Hotel',
  shop: '🛍️ Trgovina',
};

export const CITY_LIST = ['Zagreb', 'Split', 'Rijeka', 'Osijek', 'Zadar', 'Pula', 'Dubrovnik'] as const;

export const mockDogFriendlyLocations: DogFriendlyLocation[] = [
  // ─── Zagreb (10) ──────────────────────────────────────────────
  {
    id: 'df-001',
    name: 'Cogito Coffee',
    city: 'Zagreb',
    category: 'cafe',
    address: 'Varšavska ul. 11, 10000 Zagreb',
    lat: 45.8106,
    lng: 15.9723,
    rating: 4.7,
    reviewCount: 142,
    description:
      'Specialty kava u srcu grada. Psi su dobrodošli na prostranoj terasi, a osoblje uvijek ima poslastice za četveronožne goste.',
    tags: ['Vrt/terasa', 'Zdjelica za vodu', 'Wi-Fi'],
    googleMapsUrl: 'https://maps.google.com/?q=45.8106,15.9723',
    imageGradient: 'from-orange-400 to-amber-300',
  },
  {
    id: 'df-002',
    name: 'Velvet Café',
    city: 'Zagreb',
    category: 'cafe',
    address: 'Dežmanova ul. 9, 10000 Zagreb',
    lat: 45.8131,
    lng: 15.9746,
    rating: 4.5,
    reviewCount: 98,
    description:
      'Ugodna atmosfera s baršunastim foteljama i mirnim kutkom za pse. Savršeno mjesto za kavu s najboljim prijateljem.',
    tags: ['Vrt/terasa', 'Zdjelica za vodu', 'Psići dobrodošli unutra'],
    googleMapsUrl: 'https://maps.google.com/?q=45.8131,15.9746',
    imageGradient: 'from-purple-400 to-pink-300',
  },
  {
    id: 'df-003',
    name: 'Botanist',
    city: 'Zagreb',
    category: 'cafe',
    address: 'Masarykova ul. 19, 10000 Zagreb',
    lat: 45.8118,
    lng: 15.9695,
    rating: 4.6,
    reviewCount: 76,
    description:
      'Kafić s biljnim dekorom i prirodnim svjetlom. Psi su uvijek dobrodošli, posebno na sunčanoj terasi.',
    tags: ['Vrt/terasa', 'Zdjelica za vodu', 'Wi-Fi'],
    googleMapsUrl: 'https://maps.google.com/?q=45.8118,15.9695',
    imageGradient: 'from-emerald-400 to-green-300',
  },
  {
    id: 'df-004',
    name: 'Johann Franck',
    city: 'Zagreb',
    category: 'restaurant',
    address: 'Trg bana Josipa Jelačića 9, 10000 Zagreb',
    lat: 45.8131,
    lng: 15.9775,
    rating: 4.3,
    reviewCount: 189,
    description:
      'Restoran na glavnom trgu s prostranom terasom. Psi su dopušteni na vanjskom dijelu uz zdjelicu vode.',
    tags: ['Vrt/terasa', 'Zdjelica za vodu', 'Parking'],
    googleMapsUrl: 'https://maps.google.com/?q=45.8131,15.9775',
    imageGradient: 'from-teal-400 to-cyan-300',
  },
  {
    id: 'df-005',
    name: 'Mundoaka Street Food',
    city: 'Zagreb',
    category: 'restaurant',
    address: 'Petrinjska ul. 2, 10000 Zagreb',
    lat: 45.8098,
    lng: 15.9789,
    rating: 4.4,
    reviewCount: 121,
    description:
      'Kreativna street food kuhinja u ležernom ambijentu. Mali psi dobrodošli unutra, svi na terasi.',
    tags: ['Vrt/terasa', 'Psići dobrodošli unutra', 'Zdjelica za vodu'],
    googleMapsUrl: 'https://maps.google.com/?q=45.8098,15.9789',
    imageGradient: 'from-rose-400 to-red-300',
  },
  {
    id: 'df-006',
    name: 'Maksimir Park',
    city: 'Zagreb',
    category: 'park',
    address: 'Maksimirska cesta, 10000 Zagreb',
    lat: 45.8228,
    lng: 16.0178,
    rating: 4.8,
    reviewCount: 200,
    description:
      'Najveći i najstariji javni park u Zagrebu. Kilometri staza kroz šumu, jezera i livade — raj za šetnju sa psom.',
    tags: ['Šetnica', 'Igralište za pse', 'Sjenilo', 'Parking'],
    googleMapsUrl: 'https://maps.google.com/?q=45.8228,16.0178',
    imageGradient: 'from-emerald-400 to-green-300',
  },
  {
    id: 'df-007',
    name: 'Bundek Lake',
    city: 'Zagreb',
    category: 'park',
    address: 'Bundek, 10000 Zagreb',
    lat: 45.7915,
    lng: 15.9816,
    rating: 4.5,
    reviewCount: 167,
    description:
      'Park uz jezero s uređenim stazama i travnatim površinama. Omiljeno mjesto za šetnju i igranje pasa.',
    tags: ['Šetnica', 'Zdjelica za vodu', 'Igralište za pse', 'Parking'],
    googleMapsUrl: 'https://maps.google.com/?q=45.7915,15.9816',
    imageGradient: 'from-blue-400 to-sky-300',
  },
  {
    id: 'df-008',
    name: 'Jarun Lake',
    city: 'Zagreb',
    category: 'park',
    address: 'Jarunska ul., 10000 Zagreb',
    lat: 45.7818,
    lng: 15.9256,
    rating: 4.7,
    reviewCount: 185,
    description:
      'Rekreacijsko područje uz jezero s mnogo prostora za trčanje. Psi se mogu kupati na određenim dijelovima obale.',
    tags: ['Šetnica', 'Na plaži', 'Igralište za pse', 'Parking', 'Sjenilo'],
    googleMapsUrl: 'https://maps.google.com/?q=45.7818,15.9256',
    imageGradient: 'from-teal-400 to-cyan-300',
  },
  {
    id: 'df-009',
    name: 'Hotel & Dog Zagreb',
    city: 'Zagreb',
    category: 'hotel',
    address: 'Savska cesta 42, 10000 Zagreb',
    lat: 45.8035,
    lng: 15.9660,
    rating: 4.2,
    reviewCount: 53,
    description:
      'Boutique hotel koji prima goste s ljubimcima bez dodatne naknade. Krevetić, zdjelice i poslastice na recepciji.',
    tags: ['Psići dobrodošli unutra', 'Zdjelica za vodu', 'Parking', 'Wi-Fi'],
    googleMapsUrl: 'https://maps.google.com/?q=45.8035,15.9660',
    imageGradient: 'from-indigo-400 to-violet-300',
  },
  {
    id: 'df-010',
    name: 'ZooPet Shop Zagreb',
    city: 'Zagreb',
    category: 'shop',
    address: 'Ilica 50, 10000 Zagreb',
    lat: 45.8128,
    lng: 15.9668,
    rating: 4.4,
    reviewCount: 62,
    description:
      'Trgovina za kućne ljubimce s velikim izborom premium hrane, igračaka i opreme. Osoblje voli pse!',
    tags: ['Psići dobrodošli unutra', 'Zdjelica za vodu', 'Rampa za invalide'],
    googleMapsUrl: 'https://maps.google.com/?q=45.8128,15.9668',
    imageGradient: 'from-orange-400 to-amber-300',
  },

  // ─── Split (7) ────────────────────────────────────────────────
  {
    id: 'df-011',
    name: 'Kašjuni Beach',
    city: 'Split',
    category: 'beach',
    address: 'Šetalište Ivana Meštrovića, 21000 Split',
    lat: 43.5028,
    lng: 16.4143,
    rating: 4.6,
    reviewCount: 134,
    description:
      'Prelijepa šljunčana plaža u sjeni borova ispod Marjana. Psi smiju na plaži izvan glavne sezone.',
    tags: ['Na plaži', 'Sjenilo', 'Šetnica', 'Bezvodna zona'],
    googleMapsUrl: 'https://maps.google.com/?q=43.5028,16.4143',
    imageGradient: 'from-blue-400 to-sky-300',
  },
  {
    id: 'df-012',
    name: 'Žnjan Beach',
    city: 'Split',
    category: 'beach',
    address: 'Put Žnjana, 21000 Split',
    lat: 43.5010,
    lng: 16.4752,
    rating: 4.3,
    reviewCount: 108,
    description:
      'Dugačka plaža s posebnim dog-friendly dijelom. Plitka voda idealna za pse koji vole plivanje.',
    tags: ['Na plaži', 'Parking', 'Zdjelica za vodu', 'Igralište za pse'],
    googleMapsUrl: 'https://maps.google.com/?q=43.5010,16.4752',
    imageGradient: 'from-teal-400 to-cyan-300',
  },
  {
    id: 'df-013',
    name: 'Figa Food Bar',
    city: 'Split',
    category: 'cafe',
    address: 'Buvinina ul. 1, 21000 Split',
    lat: 43.5081,
    lng: 16.4402,
    rating: 4.5,
    reviewCount: 87,
    description:
      'Trendi kafić s domaćim kolačima i odličnom kavom. Terasa s pogledom na staru jezgru prima i pse.',
    tags: ['Vrt/terasa', 'Zdjelica za vodu', 'Wi-Fi'],
    googleMapsUrl: 'https://maps.google.com/?q=43.5081,16.4402',
    imageGradient: 'from-rose-400 to-red-300',
  },
  {
    id: 'df-014',
    name: 'Bokeria Kitchen & Wine',
    city: 'Split',
    category: 'restaurant',
    address: 'Domaldova ul. 8, 21000 Split',
    lat: 43.5086,
    lng: 16.4389,
    rating: 4.7,
    reviewCount: 156,
    description:
      'Moderni restoran s mediteranskom kuhinjom. Psi dobrodošli na terasi uz zvukove grada.',
    tags: ['Vrt/terasa', 'Zdjelica za vodu'],
    googleMapsUrl: 'https://maps.google.com/?q=43.5086,16.4389',
    imageGradient: 'from-purple-400 to-pink-300',
  },
  {
    id: 'df-015',
    name: 'Marjan Park',
    city: 'Split',
    category: 'park',
    address: 'Šetalište Marka Marulića, 21000 Split',
    lat: 43.5092,
    lng: 16.4208,
    rating: 4.9,
    reviewCount: 195,
    description:
      'Šumski park na poluotoku Marjanu s brojnim stazama i pogledom na more. Psi obožavaju borovu šumu.',
    tags: ['Šetnica', 'Sjenilo', 'Bezvodna zona', 'Igralište za pse'],
    googleMapsUrl: 'https://maps.google.com/?q=43.5092,16.4208',
    imageGradient: 'from-emerald-400 to-green-300',
  },
  {
    id: 'df-016',
    name: 'Lvxor Café',
    city: 'Split',
    category: 'cafe',
    address: 'Peristil, 21000 Split',
    lat: 43.5081,
    lng: 16.4406,
    rating: 4.4,
    reviewCount: 112,
    description:
      'Kultni kafić na Peristilu Dioklecijanove palače. Mali psi dobrodošli — ispijajte kavu okruženi antičkim stupovima.',
    tags: ['Vrt/terasa', 'Zdjelica za vodu', 'Psići dobrodošli unutra'],
    googleMapsUrl: 'https://maps.google.com/?q=43.5081,16.4406',
    imageGradient: 'from-orange-400 to-amber-300',
  },
  {
    id: 'df-017',
    name: 'Dog City Split',
    city: 'Split',
    category: 'shop',
    address: 'Vukovarska ul. 22, 21000 Split',
    lat: 43.5115,
    lng: 16.4490,
    rating: 4.3,
    reviewCount: 41,
    description:
      'Specijalizirana trgovina za pse s premium hranom, opremom za šetnju i modnim dodacima za ljubimce.',
    tags: ['Psići dobrodošli unutra', 'Zdjelica za vodu', 'Parking'],
    googleMapsUrl: 'https://maps.google.com/?q=43.5115,16.4490',
    imageGradient: 'from-indigo-400 to-violet-300',
  },

  // ─── Rijeka (7) ───────────────────────────────────────────────
  {
    id: 'df-018',
    name: 'Cukarikafe',
    city: 'Rijeka',
    category: 'cafe',
    address: 'Korzo 28, 51000 Rijeka',
    lat: 45.3271,
    lng: 14.4422,
    rating: 4.5,
    reviewCount: 73,
    description:
      'Šarmantni kafić na glavnoj riječkoj šetnici. Psi su dobrodošli na terasi, a zimi i unutra.',
    tags: ['Vrt/terasa', 'Psići dobrodošli unutra', 'Zdjelica za vodu', 'Wi-Fi'],
    googleMapsUrl: 'https://maps.google.com/?q=45.3271,14.4422',
    imageGradient: 'from-teal-400 to-cyan-300',
  },
  {
    id: 'df-019',
    name: 'Grad Pub',
    city: 'Rijeka',
    category: 'cafe',
    address: 'Riva 12, 51000 Rijeka',
    lat: 45.3268,
    lng: 14.4430,
    rating: 4.2,
    reviewCount: 56,
    description:
      'Opušteni pub na rivi s pogledom na luku. Craft pivo i mirna atmosfera idealna za vlasnika i psa.',
    tags: ['Vrt/terasa', 'Zdjelica za vodu'],
    googleMapsUrl: 'https://maps.google.com/?q=45.3268,14.4430',
    imageGradient: 'from-purple-400 to-pink-300',
  },
  {
    id: 'df-020',
    name: 'Kantrida Beach',
    city: 'Rijeka',
    category: 'beach',
    address: 'Šetalište XIII. Divizije, 51000 Rijeka',
    lat: 45.3336,
    lng: 14.4126,
    rating: 4.1,
    reviewCount: 67,
    description:
      'Kamena plaža zapadno od centra. Poseban dio plaže namijenjen je vlasnicima sa psima.',
    tags: ['Na plaži', 'Šetnica', 'Parking'],
    googleMapsUrl: 'https://maps.google.com/?q=45.3336,14.4126',
    imageGradient: 'from-blue-400 to-sky-300',
  },
  {
    id: 'df-021',
    name: 'Lungo Mare',
    city: 'Rijeka',
    category: 'park',
    address: 'Šetalište XIII. Divizije, 51000 Rijeka',
    lat: 45.3310,
    lng: 14.4215,
    rating: 4.8,
    reviewCount: 178,
    description:
      'Legendarna obalna šetnica od Voloskog do Opatije. Savršena za dugačke šetnje uz more s vašim psom.',
    tags: ['Šetnica', 'Sjenilo', 'Na plaži'],
    googleMapsUrl: 'https://maps.google.com/?q=45.3310,14.4215',
    imageGradient: 'from-emerald-400 to-green-300',
  },
  {
    id: 'df-022',
    name: 'Mlaka Park',
    city: 'Rijeka',
    category: 'park',
    address: 'Mlaka, 51000 Rijeka',
    lat: 45.3285,
    lng: 14.4380,
    rating: 4.0,
    reviewCount: 34,
    description:
      'Mirni zeleni park u četvrti Mlaka. Idealan za kratku šetnju s psom i odmor na klupi.',
    tags: ['Šetnica', 'Sjenilo', 'Igralište za pse'],
    googleMapsUrl: 'https://maps.google.com/?q=45.3285,14.4380',
    imageGradient: 'from-lime-400 to-green-300',
  },
  {
    id: 'df-023',
    name: 'Morski Pas',
    city: 'Rijeka',
    category: 'restaurant',
    address: 'Riva 16, 51000 Rijeka',
    lat: 45.3265,
    lng: 14.4445,
    rating: 4.3,
    reviewCount: 92,
    description:
      'Riblji restoran na rivi s imenom koje obećava — Morski Pas. Terasa prima pse, naravno.',
    tags: ['Vrt/terasa', 'Zdjelica za vodu', 'Na plaži'],
    googleMapsUrl: 'https://maps.google.com/?q=45.3265,14.4445',
    imageGradient: 'from-rose-400 to-red-300',
  },
  {
    id: 'df-024',
    name: 'Belveder Hotel',
    city: 'Rijeka',
    category: 'hotel',
    address: 'Šetalište XIII. Divizije 62, 51000 Rijeka',
    lat: 45.3341,
    lng: 14.4072,
    rating: 4.1,
    reviewCount: 28,
    description:
      'Elegantan hotel blizu centra koji prima ljubimce. Vrt i blizina šetnice idealni za jutarnju šetnju.',
    tags: ['Psići dobrodošli unutra', 'Zdjelica za vodu', 'Parking', 'Wi-Fi'],
    googleMapsUrl: 'https://maps.google.com/?q=45.3341,14.4072',
    imageGradient: 'from-indigo-400 to-violet-300',
  },

  // ─── Osijek (4) ───────────────────────────────────────────────
  {
    id: 'df-025',
    name: 'Promenada',
    city: 'Osijek',
    category: 'park',
    address: 'Promenada ul., 31000 Osijek',
    lat: 45.5539,
    lng: 18.6952,
    rating: 4.6,
    reviewCount: 143,
    description:
      'Prekrasna šetnica uz Dravu u srcu Osijeka. Široke staze i zelenilo čine ju omiljenom za šetače sa psima.',
    tags: ['Šetnica', 'Sjenilo', 'Igralište za pse', 'Zdjelica za vodu'],
    googleMapsUrl: 'https://maps.google.com/?q=45.5539,18.6952',
    imageGradient: 'from-emerald-400 to-green-300',
  },
  {
    id: 'df-026',
    name: 'Waldinger',
    city: 'Osijek',
    category: 'cafe',
    address: 'Županijska ul. 8, 31000 Osijek',
    lat: 45.5556,
    lng: 18.6944,
    rating: 4.4,
    reviewCount: 88,
    description:
      'Povijesni kafić u secesijskom zdanju. Terasa na glavnoj ulici prima goste s dobro odgojenim psima.',
    tags: ['Vrt/terasa', 'Zdjelica za vodu', 'Wi-Fi'],
    googleMapsUrl: 'https://maps.google.com/?q=45.5556,18.6944',
    imageGradient: 'from-orange-400 to-amber-300',
  },
  {
    id: 'df-027',
    name: 'Copacabana Osijek',
    city: 'Osijek',
    category: 'beach',
    address: 'Šetalište kardinala Franje Šepera, 31000 Osijek',
    lat: 45.5595,
    lng: 18.7015,
    rating: 4.2,
    reviewCount: 65,
    description:
      'Riječna plaža na Dravi s pijeskom i travom. Ima poseban dio za pse koji vole vodu.',
    tags: ['Na plaži', 'Parking', 'Igralište za pse', 'Zdjelica za vodu'],
    googleMapsUrl: 'https://maps.google.com/?q=45.5595,18.7015',
    imageGradient: 'from-blue-400 to-sky-300',
  },
  {
    id: 'df-028',
    name: 'Old Bridge Pub',
    city: 'Osijek',
    category: 'restaurant',
    address: 'Trg Svetog Trojstva 6, Tvrđa, 31000 Osijek',
    lat: 45.5603,
    lng: 18.7110,
    rating: 4.0,
    reviewCount: 47,
    description:
      'Pub u baroknoj tvrđi s velikim dvorištem. Opuštena atmosfera gdje su psi dio obitelji.',
    tags: ['Vrt/terasa', 'Zdjelica za vodu', 'Psići dobrodošli unutra'],
    googleMapsUrl: 'https://maps.google.com/?q=45.5603,18.7110',
    imageGradient: 'from-purple-400 to-pink-300',
  },

  // ─── Zadar (4) ────────────────────────────────────────────────
  {
    id: 'df-029',
    name: 'Morske Orgulje Area',
    city: 'Zadar',
    category: 'park',
    address: 'Obala Petra Krešimira IV, 23000 Zadar',
    lat: 44.1194,
    lng: 15.2214,
    rating: 4.8,
    reviewCount: 170,
    description:
      'Obalna šetnica kod čuvenih Morskih orgulja. Zvukovi mora i svježeg zraka idealni za šetnju s psom uz zalazak sunca.',
    tags: ['Šetnica', 'Na plaži', 'Sjenilo'],
    googleMapsUrl: 'https://maps.google.com/?q=44.1194,15.2214',
    imageGradient: 'from-teal-400 to-cyan-300',
  },
  {
    id: 'df-030',
    name: 'Garden Lounge',
    city: 'Zadar',
    category: 'cafe',
    address: 'Bedemi zadarskih pobuna, 23000 Zadar',
    lat: 44.1158,
    lng: 15.2244,
    rating: 4.5,
    reviewCount: 95,
    description:
      'Chic lounge bar na bedemima starog grada s pogledom na more. Psi su dobrodošli na terasi.',
    tags: ['Vrt/terasa', 'Zdjelica za vodu', 'Wi-Fi', 'Sjenilo'],
    googleMapsUrl: 'https://maps.google.com/?q=44.1158,15.2244',
    imageGradient: 'from-rose-400 to-red-300',
  },
  {
    id: 'df-031',
    name: 'Kolovare Beach',
    city: 'Zadar',
    category: 'beach',
    address: 'Ul. Bože Peričića, 23000 Zadar',
    lat: 44.1098,
    lng: 15.2352,
    rating: 4.1,
    reviewCount: 79,
    description:
      'Popularna gradska plaža s dijelom za pse. Kombinacija pijeska i šljunka, lako dostupna iz centra.',
    tags: ['Na plaži', 'Parking', 'Zdjelica za vodu'],
    googleMapsUrl: 'https://maps.google.com/?q=44.1098,15.2352',
    imageGradient: 'from-blue-400 to-sky-300',
  },
  {
    id: 'df-032',
    name: 'Arsenal',
    city: 'Zadar',
    category: 'restaurant',
    address: 'Trg tri bunara 1, 23000 Zadar',
    lat: 44.1153,
    lng: 15.2258,
    rating: 4.6,
    reviewCount: 131,
    description:
      'Restoran u povijesnom arsenalu s visokim stropovima i prostranom terasom. Psi su dio zadarske scene.',
    tags: ['Vrt/terasa', 'Zdjelica za vodu', 'Rampa za invalide'],
    googleMapsUrl: 'https://maps.google.com/?q=44.1153,15.2258',
    imageGradient: 'from-orange-400 to-amber-300',
  },

  // ─── Pula (4) ─────────────────────────────────────────────────
  {
    id: 'df-033',
    name: 'Verudela Beach',
    city: 'Pula',
    category: 'beach',
    address: 'Verudela, 52100 Pula',
    lat: 44.8386,
    lng: 13.8268,
    rating: 4.4,
    reviewCount: 102,
    description:
      'Kamena plaža na poluotoku Verudeli s kristalno čistim morem. Psi imaju svoj kutak za kupanje.',
    tags: ['Na plaži', 'Parking', 'Šetnica', 'Sjenilo'],
    googleMapsUrl: 'https://maps.google.com/?q=44.8386,13.8268',
    imageGradient: 'from-teal-400 to-cyan-300',
  },
  {
    id: 'df-034',
    name: 'Cabahia',
    city: 'Pula',
    category: 'cafe',
    address: 'Riva 2, 52100 Pula',
    lat: 44.8666,
    lng: 13.8425,
    rating: 4.3,
    reviewCount: 68,
    description:
      'Kafić na rivi s pogledom na luku i brodove. Psi uživaju u morskom zraku na sunčanoj terasi.',
    tags: ['Vrt/terasa', 'Zdjelica za vodu', 'Wi-Fi'],
    googleMapsUrl: 'https://maps.google.com/?q=44.8666,13.8425',
    imageGradient: 'from-purple-400 to-pink-300',
  },
  {
    id: 'df-035',
    name: 'Gradski Park Pula',
    city: 'Pula',
    category: 'park',
    address: 'Ul. Sergijevaca, 52100 Pula',
    lat: 44.8687,
    lng: 13.8465,
    rating: 4.2,
    reviewCount: 55,
    description:
      'Zeleni park u blizini Arene s hladovinom starih stabala. Omiljeno mjesto za lokalne šetače sa psima.',
    tags: ['Šetnica', 'Sjenilo', 'Igralište za pse'],
    googleMapsUrl: 'https://maps.google.com/?q=44.8687,13.8465',
    imageGradient: 'from-emerald-400 to-green-300',
  },
  {
    id: 'df-036',
    name: 'Batelina',
    city: 'Pula',
    category: 'restaurant',
    address: 'Čimulje 25, 52100 Pula',
    lat: 44.8458,
    lng: 13.8340,
    rating: 4.8,
    reviewCount: 148,
    description:
      'Poznati riblji restoran s dog-friendly terasom. Svježa riba iz Jadrana u opuštenom okruženju.',
    tags: ['Vrt/terasa', 'Zdjelica za vodu', 'Parking'],
    googleMapsUrl: 'https://maps.google.com/?q=44.8458,13.8340',
    imageGradient: 'from-rose-400 to-red-300',
  },

  // ─── Dubrovnik (3) ────────────────────────────────────────────
  {
    id: 'df-037',
    name: 'Lapad Beach',
    city: 'Dubrovnik',
    category: 'beach',
    address: 'Lapad, 20000 Dubrovnik',
    lat: 42.6558,
    lng: 18.0672,
    rating: 4.3,
    reviewCount: 89,
    description:
      'Šljunčana plaža na poluotoku Lapadu. Manje gužve nego u Starom gradu, s dijelom za pse u ranim satima.',
    tags: ['Na plaži', 'Šetnica', 'Parking', 'Sjenilo'],
    googleMapsUrl: 'https://maps.google.com/?q=42.6558,18.0672',
    imageGradient: 'from-blue-400 to-sky-300',
  },
  {
    id: 'df-038',
    name: 'Gradac Park',
    city: 'Dubrovnik',
    category: 'park',
    address: 'Ul. od Tabakarije, 20000 Dubrovnik',
    lat: 42.6421,
    lng: 18.1032,
    rating: 4.7,
    reviewCount: 115,
    description:
      'Park iznad mora s pogledom na gradske zidine i otok Lokrum. Borova šuma pruža ugodnu hladovinu za šetnju.',
    tags: ['Šetnica', 'Sjenilo', 'Na plaži'],
    googleMapsUrl: 'https://maps.google.com/?q=42.6421,18.1032',
    imageGradient: 'from-emerald-400 to-green-300',
  },
  {
    id: 'df-039',
    name: 'Buža Bar Area',
    city: 'Dubrovnik',
    category: 'cafe',
    address: 'Ul. od Margarite, 20000 Dubrovnik',
    lat: 42.6397,
    lng: 18.1087,
    rating: 3.9,
    reviewCount: 42,
    description:
      'Prostor oko poznatog Buža bara izvan gradskih zidina. Mali psi na povodcu dopušteni, s pogledom na otvoreno more.',
    tags: ['Vrt/terasa', 'Na plaži', 'Zdjelica za vodu'],
    googleMapsUrl: 'https://maps.google.com/?q=42.6397,18.1087',
    imageGradient: 'from-indigo-400 to-violet-300',
  },
];
